/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package LinkedList;

public class App {

    public static void main(String[] args) {

        checkLinkedList("my Rad String");

    }

    public static void checkLinkedList(String value) {
        LinkedList testList = new LinkedList();
        testList.insert(value);

        testList.insert("another good string");

        testList.includes("my Rad String");

    }
}
