/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package LinkedList;

public class App {

    public static void main(String[] args) {

        String getGreeting = "Hello World";

        System.out.println(getGreeting);
        checkLinkedList("my rad string");
    }

    public static void checkLinkedList(String value) {
        LinkedList testList = new LinkedList(value);
        System.out.println(testList.head.value);

        testList.insert("another good string");

        System.out.println(testList.head.value);
        System.out.println(testList.head.reference);

    }
}
